//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oppenheimer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Chrome Browser~chrome~true~0~Seconds~false~false~,Chrome Driver~chromedriver~true~0~Seconds~false~false~,Excel~EXCEL.EXE~true~0~Seconds~false~false~,Phantom JS~phantomjs~true~0~Seconds~false~false~,Phantom JS Error~WerFault~true~0~Seconds~false~false~,UFT Helper~HP.UFT.HelperService~true~0~Seconds~false~false~,Internet Explorer~iexplore~true~0~Seconds~false~false~,ALM~ALM-Client~true~0~Seconds~false~false~,UFT Tool~UFT~true~0~Seconds~false~false~,Auto Chrome~chrome~false~5~Minutes~true~false~,Auto Chrome Driver~chromedriver~false~5~Minutes~true~false~")]
        public string Apps {
            get {
                return ((string)(this["Apps"]));
            }
            set {
                this["Apps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Temp\\")]
        public string LogPath {
            get {
                return ((string)(this["LogPath"]));
            }
            set {
                this["LogPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MinOnOpen {
            get {
                return ((bool)(this["MinOnOpen"]));
            }
            set {
                this["MinOnOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public string CycleTimeInt {
            get {
                return ((string)(this["CycleTimeInt"]));
            }
            set {
                this["CycleTimeInt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Seconds")]
        public string CycleTimeType {
            get {
                return ((string)(this["CycleTimeType"]));
            }
            set {
                this["CycleTimeType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AgentOnOpen {
            get {
                return ((bool)(this["AgentOnOpen"]));
            }
            set {
                this["AgentOnOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string RetryTime {
            get {
                return ((string)(this["RetryTime"]));
            }
            set {
                this["RetryTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string RetryCount {
            get {
                return ((string)(this["RetryCount"]));
            }
            set {
                this["RetryCount"] = value;
            }
        }
    }
}
